# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_delete_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('ArticleID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=256, verbose_name='文章标题')),
                ('Author', models.CharField(max_length=256, verbose_name='作者')),
                ('Content', models.TextField(verbose_name='文章内容')),
                ('PublishDate', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('CategoryID', models.IntegerField(verbose_name='类别')),
                ('isCheck', models.IntegerField(default=1)),
                ('isTop', models.IntegerField(default=0)),
                ('Count', models.IntegerField(default=1, null=True)),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
