# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_auto_20161205_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='CategoryID',
            field=models.IntegerField(verbose_name='类别'),
        ),
    ]
