# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_auto_20161205_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='CategoryID',
        ),
        migrations.AddField(
            model_name='articles',
            name='CategoryID',
            field=models.ManyToManyField(to='women.Categories', verbose_name='所属类别'),
        ),
    ]
