# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0006_auto_20161205_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cites',
            fields=[
                ('CityID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=56, verbose_name='城市名字')),
                ('Rank', models.IntegerField(blank=True, unique=True, verbose_name='顺序')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
    ]
