# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0007_cites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cites',
            new_name='Cities',
        ),
    ]
