# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0008_auto_20161205_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityNews',
            fields=[
                ('CityNewID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=56, verbose_name='标题')),
                ('Author', models.CharField(max_length=56, verbose_name='作者')),
                ('Content', models.TextField(verbose_name='内容')),
                ('PublishDate', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('CityID', models.IntegerField(verbose_name='城市')),
                ('isCheck', models.IntegerField(default=1)),
                ('Count', models.IntegerField(default=1, null=True)),
            ],
            options={
                'verbose_name': '市州动态',
                'verbose_name_plural': '市州动态',
            },
        ),
    ]
