# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0013_auto_20161205_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('PId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=56, verbose_name='姓名')),
                ('Position', models.CharField(max_length=56, verbose_name='职务')),
                ('Content', models.TextField(verbose_name='留言内容')),
                ('BranchID', models.IntegerField(blank=True, unique=True, verbose_name='职务ID')),
                ('isCheck', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': '理事会机构',
                'verbose_name': '理事会机构',
            },
        ),
        migrations.AlterModelOptions(
            name='branches',
            options={'verbose_name': '理事会机构ID', 'verbose_name_plural': '理事会机构ID'},
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': '市州ID', 'verbose_name_plural': '市州ID'},
        ),
    ]
