# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0015_auto_20161205_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='BranchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='women.Branches'),
        ),
    ]
