# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0016_auto_20161205_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProCates',
            fields=[
                ('ProCateID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=56, verbose_name='慈善类型')),
            ],
            options={
                'verbose_name': '慈善类型',
                'verbose_name_plural': '慈善类型',
            },
        ),
    ]
