# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0017_procates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('ProID', models.AutoField(primary_key=True, serialize=False)),
                ('ProName', models.CharField(max_length=56, verbose_name='慈善项目')),
                ('Author', models.CharField(max_length=50, null=True, verbose_name='作者')),
                ('Content', models.TextField(verbose_name='内容')),
                ('ImgURL', models.CharField(max_length=500, verbose_name='图片链接')),
                ('IsFriend', models.CharField(max_length=10)),
                ('Time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('YearID', models.IntegerField(default=0)),
                ('ProCateID', models.IntegerField(default=0)),
                ('IsIndex', models.CharField(default='false', max_length=50)),
                ('IsCheck', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': '慈善项目',
                'verbose_name': '慈善项目',
            },
        ),
    ]
