# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0018_projects'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procates',
            options={'verbose_name': '公益类型ID', 'verbose_name_plural': '公益类型ID'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': '公益项目', 'verbose_name_plural': '公益项目'},
        ),
        migrations.AlterField(
            model_name='projects',
            name='ProName',
            field=models.CharField(max_length=56, verbose_name='公益项目'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='YearID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='women.ProCates'),
        ),
    ]
