# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0024_auto_20161205_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='ProCateID',
            field=models.IntegerField(default=0),
        ),
    ]
