# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0028_remove_projects_yearid'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='YearID',
            field=models.IntegerField(default=0),
        ),
    ]
