# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0033_qrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=56, verbose_name='用户名')),
                ('Password', models.CharField(max_length=56, verbose_name='密码')),
                ('IsSuper', models.CharField(max_length=56)),
            ],
            options={
                'verbose_name_plural': '用户',
                'verbose_name': '用户',
            },
        ),
    ]
