# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0034_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('VideoID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=56, verbose_name='标题')),
                ('Author', models.CharField(max_length=56, verbose_name='作者')),
                ('Content', models.TextField(verbose_name='内容')),
                ('Time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('FilePath', models.CharField(max_length=56, verbose_name='视频路径')),
                ('Rank', models.IntegerField(blank=True, null=True, verbose_name='顺序')),
                ('Isindex', models.CharField(max_length=56)),
                ('PicPath', models.CharField(max_length=56, verbose_name='图片路径')),
                ('Count', models.IntegerField(blank=True, default=1)),
            ],
            options={
                'verbose_name': '爱心视频',
                'verbose_name_plural': '爱心视频',
            },
        ),
    ]
