# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0037_auto_20161206_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='CategoryID',
        ),
        migrations.AddField(
            model_name='articles',
            name='CategoryID',
            field=models.IntegerField(default=1, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
