# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0039_auto_20161206_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='CategoryID',
            field=models.IntegerField(verbose_name='ID'),
        ),
    ]
