# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 16:15
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0042_auto_20161206_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouts',
            name='Content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容'),
        ),
    ]
