# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0045_auto_20161207_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branches',
            options={'ordering': ['BranchID'], 'verbose_name': '理事会职位', 'verbose_name_plural': '理事会职位'},
        ),
    ]
