# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 11:55
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0046_auto_20161207_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='Content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容'),
        ),
    ]
