# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0047_auto_20161207_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='isCheck',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1),
        ),
    ]
