# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0048_auto_20161207_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='isCheck',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='是否审核'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='isTop',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='是否置顶'),
        ),
    ]
