# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0049_auto_20161207_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='Count',
            field=models.IntegerField(default=1, null=True, verbose_name='阅读次数'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='CategoryID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='文章分类'),
        ),
    ]
