# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 12:24
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0050_auto_20161207_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'ordering': ['CityID'], 'verbose_name': '市州ID', 'verbose_name_plural': '市州ID'},
        ),
        migrations.AlterField(
            model_name='citynews',
            name='Content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='citynews',
            name='Count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='citynews',
            name='isCheck',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='是否审核'),
        ),
    ]
