# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0053_auto_20161207_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procates',
            options={'verbose_name': '慈善类型', 'verbose_name_plural': '慈善类型'},
        ),
        migrations.AlterModelOptions(
            name='years',
            options={'ordering': ['-YearID'], 'verbose_name': '年份', 'verbose_name_plural': '年份'},
        ),
    ]
