# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 13:08
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0055_auto_20161207_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pronews',
            name='Content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='pronews',
            name='IsCheck',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], default='0', max_length=1, verbose_name='是否审核'),
        ),
    ]
