# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 13:20
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0058_auto_20161207_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='Content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='FilePath',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='Isindex',
            field=models.CharField(choices=[('true', '是'), ('false', '否')], default='false', max_length=5, verbose_name='是否置顶'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='PicPath',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='图片'),
        ),
    ]
