# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0062_auto_20170207_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liuyans',
            name='IsShow',
            field=models.CharField(default='false', max_length=56, verbose_name='是否显示'),
        ),
    ]
